'use strict';
/**
 * The gate's suite registry — honest-test-gate #1, ADR honest-test-gate/0001 §3.
 *
 * ONE ordered list. The order is the execution order (carried over from the hand-written
 * runner this replaced), and every suite is loaded before any runs, so a suite's
 * load-time reads see today's environment whatever its position. Adding a suite is one
 * line here; the engine (test/helpers/gateRunner.js) derives every summary line and
 * every total from this list, so nothing else needs to agree with it.
 *
 *   { file, skipNote? }  file is resolved against test/; skipNote is the reason printed
 *                        when the whole suite skipped (e.g. no live stack).
 *   { name, run }        a pseudo-entry (the config smoke check).
 *
 * Every test/*.test.js file must be in `suites` or in `excluded` with a reason —
 * test/stack-free-npm-test.test.js G5 fails otherwise, so a suite can never be written
 * and then silently never run.
 */

// The config smoke check that used to run ahead of the suites (its env is set in test/test.js).
async function configLoading() {
  const { loadConfig } = require('../lib/config');
  try {
    const config = loadConfig();
    console.log('Configuration loaded successfully:', Object.keys(config));
    return { pass: 1, fail: 0 };
  } catch (error) {
    console.error('Configuration loading failed:', error.message);
    return { pass: 0, fail: 1 };
  }
}

const suites = [
  { name: 'config-loading', run: configLoading },
  { file: 'profile-tags.test.js', skipNote: 'control panel not reachable' },
  { file: 'profile-tags-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'tag-detail.test.js', skipNote: 'control panel not reachable' },
  { file: 'tag-detail-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'tag-detail-write.test.js', skipNote: 'control panel not reachable' },
  { file: 'tag-detail-write-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'tag-index.test.js', skipNote: 'control panel not reachable' },
  { file: 'tag-index-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'authored-tagging.test.js', skipNote: 'control panel not reachable' },
  { file: 'authored-tagging-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'profile-tag-polish.test.js', skipNote: 'control panel not reachable' },
  { file: 'profile-tag-polish-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'search-result-parity.test.js' },
  { file: 'search-results-url.test.js' },
  { file: 'pin-a-tag.test.js', skipNote: 'control panel not reachable' },
  { file: 'pin-a-tag-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'tl-publication-from-pins.test.js', skipNote: 'control panel not reachable' },
  { file: 'tl-publication-from-pins-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'customize-pin-curation-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'most-pinned-tag-index.test.js', skipNote: 'control panel not reachable' },
  { file: 'most-pinned-tag-index-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'tag-detail-curated-view-and-pin-polish.test.js', skipNote: 'control panel not reachable' },
  { file: 'tag-detail-curated-view-and-pin-polish-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'restore-historical-data-and-fix-tl-author-filter.test.js', skipNote: 'control panel not reachable' },
  { file: 'treasure-maps-router-preset.test.js' },
  { file: 'scheduled-search-and-house-scores-refresh.test.js' },
  { file: 'strfry-router-first-boot-config.test.js' },
  { file: 'per-query-neo4j-timeout-safety-net.test.js' },
  { file: 'nip05-checkmark-verification.test.js' },
  { file: 'publish-export-a-concept.test.js' },
  { file: 'community-reference-nostr-relay-stub.test.js' },
  { file: 'nip51-list-export-from-pins.test.js', skipNote: 'control panel not reachable' },
  { file: 'nip51-list-export-from-pins-publish.test.js', skipNote: 'preconditions not met' },
  { file: 'pin-detail-into-tag-pinned-tab.test.js' },
  { file: 'collapse-into-export-concept.test.js' },
  { file: 'login-failure-and-tag-collapse.test.js' },
  { file: 'header-conceptgraph-tag.test.js' },
  { file: 'community-reference-superset-link.test.js' },
  { file: 'graperank-shared-csv-race.test.js' },
  { file: 'community-class-thread-pull.test.js' },
  { file: 'task-queue-bullmq.test.js' },
  { file: 'task-queue-neo4j-resource-class.test.js' },
  { file: 'entrypoint-template-rendering.test.js' },
  { file: 'bullboard-admin-access.test.js' },
  { file: 'admin-tools-dashboard-panel.test.js' },
  { file: 'create-tapestry.test.js' },
  { file: 'reconciliation-incremental-mode.test.js' },
  { file: 'generalized-task-scheduler.test.js' },
  { file: 'reconciliation-rearchitecture.test.js' },
  { file: 'scheduled-tasks-with-arguments.test.js' },
  { file: 'manual-task-retrigger-after-finish.test.js' },
  { file: 'scheduled-task-timeout-propagation.test.js' },
  { file: 'kill-timeout-orphans-by-default.test.js' },
  { file: 'task-queue-semaphore-protection-audit.test.js' },
  { file: 'profile-follows-list.test.js' },
  { file: 'profile-website-link.test.js' },
  { file: 'profile-verified-followers-count.test.js' },
  { file: 'profile-followers-list.test.js' },
  { file: 'profile-verified-reporters-count.test.js' },
  { file: 'verified-reporters-membership-data.test.js' },
  { file: 'verified-reporters-list-page.test.js' },
  { file: 'profile-verified-counts-owner-pov.test.js' },
  { file: 'profile-verified-counts-explainer-and-alarm.test.js' },
  { file: 'search-api-result-type-settings.test.js' },
  { file: 'trusted-list-pin-publish-blockers.test.js' },
  { file: 'nostr-user-tag-hybrid-ea-writer.test.js' },
  { file: 'reputation-info-popup.test.js' },
  { file: 'live-feed-read-path.test.js' },
  { file: 'live-feed-feed-page.test.js' },
  { file: 'note-surfaces-read-path.test.js' },
  { file: 'note-surfaces-ui.test.js' },
  { file: 'event-page-read-path.test.js' },
  { file: 'event-page-ui.test.js' },
  { file: 'verified-reporters-report-columns.test.js' },
  { file: 'profile-identity-details-popover.test.js' },
  { file: 'profile-follows-hops.test.js' },
  { file: 'profile-hops-path.test.js' },
  { file: 'tag-read-union.test.js' },
  { file: 'b-tag-primitive.test.js' },
  { file: 'b-tag-seeds.test.js' },
  { file: 'dual-z-writer.test.js' },
  { file: 'open-ranking-stats.test.js' },
  { file: 'open-ranking-search.test.js' },
  { file: 'open-ranking-rank.test.js' },
  { file: 'open-ranking-followers-muters.test.js' },
  { file: 'verified-muters-read-api.test.js' },
  { file: 'verified-muters-profile-surface.test.js' },
  { file: 'event-tagging-core.test.js' },
  { file: 'event-tagging-spec.test.js' },
  { file: 'global-publish-gate.test.js' },
  { file: 'event-tagging-firmware-seed.test.js' },
  { file: 'event-tagging-read-api.test.js' },
  { file: 'event-tagging-write-path.test.js' },
  { file: 'event-tagging-read-viewer-stance.test.js' },
  { file: 'event-tag-note-affordance-ui.test.js' },
  { file: 'tag-actions-menu-ui.test.js' },
  { file: 'tagging-raw-event-inspector-ui.test.js' },
  { file: 'note-tagging-raw-events-inspector-ui.test.js' },
  { file: 'note-tagging-raw-events-inspector-http.test.js', skipNote: 'preconditions not met' },
  { file: 'event-tagging-for-tag.test.js' },
  { file: 'unified-tag-index.test.js' },
  { file: 'event-tagging-notes-by-author.test.js' },
  { file: 'unified-tags-directory.test.js' },
  { file: 'profile-authored-notes-ui.test.js' },
  { file: 'notes-replies-toggle.test.js' },
  { file: 'feed-pagination.test.js' },
  { file: 'profile-content-card.test.js' },
  { file: 'tag-applicability.test.js' },
  { file: 'tag-applicability-picker.test.js' },
  { file: 'note-trusted-list.test.js' },
  { file: 'profile-tag-consume-by-a-coordinate.test.js' },
  { file: 'pov-selectable-tag-surfaces.test.js' },
  { file: 'pov-resolution-status.test.js' },
  { file: 'pov-rank-threshold-key.test.js' },
  { file: 'pov-notice-text.test.js' },
  { file: 'pov-state-unification.test.js' },
  { file: 'applicability-republish.test.js' },
  { file: 'harness-lint.test.js' },
  { file: 'harness-stats.test.js' },
  { file: 'session-start.test.js' },
  { file: 'stack-free-npm-test.test.js' },
  { file: 'ci-test-job.test.js' },
  { file: 'sync-panel-tag-filters.test.js' },
  { file: 'router-stream-tag-filters.test.js' },
  { file: 'deploy-safety-status.test.js', skipNote: 'preconditions not met' },
  { file: 'safe-to-merge-check.test.js' },
  { file: 'next-task-countdown.test.js' },
  { file: 'close-unauth-write-surface.test.js' },
  { file: 'default-deny-mutations.test.js' },
  { file: 'login-signature-verification.test.js' },
  { file: 'publish-event-signature-verification.test.js' },
  { file: 'users-page-neo4j-endpoint.test.js' },
  { file: 'strfry-wipe-owner-gate.test.js' },
  { file: 'relationship-primitives.test.js', skipNote: 'preconditions not met' },
  { file: 'relationship-primitives-probe.test.js', skipNote: 'preconditions not met' },
  { file: 'event-less-create-set.test.js', skipNote: 'preconditions not met' },
  { file: 'strfry-write-assertion-bracket.test.js', skipNote: 'preconditions not met' },
  { file: 'move-nodes-between-sets-ui.test.js', skipNote: 'preconditions not met' },
  { file: 'capture-a-goal-and-see-it.test.js', skipNote: 'preconditions not met' },
  { file: 'firmware-concept-elements-sets.test.js', skipNote: 'preconditions not met' },
  { file: 'tapestry-per-concept-detail-views.test.js', skipNote: 'preconditions not met' },
  { file: 'structures-the-brain-can-trust.test.js', skipNote: 'preconditions not met' },
  { file: 'break-a-goal-into-pieces.test.js', skipNote: 'preconditions not met' },
  { file: 'attach-the-world.test.js', skipNote: 'preconditions not met' },
  { file: 'sessions-read-the-brain.test.js', skipNote: 'preconditions not met' },
  { file: 'the-proposal-loop.test.js', skipNote: 'preconditions not met' },
  { file: 'teach-it-what-matters.test.js', skipNote: 'preconditions not met' },
  { file: 'the-brain-survives.test.js', skipNote: 'preconditions not met' },
  { file: 'operational-direction.test.js', skipNote: 'preconditions not met' },
  { file: 'store-the-four-when-a-goal-is-captured-or-updated.test.js', skipNote: 'preconditions not met' },
  { file: 'return-the-four-on-every-read-surface.test.js', skipNote: 'preconditions not met' },
  { file: 'show-the-four-on-the-goal-screens-that-already-exist.test.js', skipNote: 'preconditions not met' },
  { file: 'in-app-badged-ta-avatar.test.js' },
  { file: 'recognizable-published-ta-profile.test.js' },
  { file: 'stamped-composite-avatar.test.js' },
  { file: 'tapestry-key-put-await.test.js' },
  { file: 'add-a-concept-to-a-tapestry.test.js' },
  { file: 'take-a-concept-back-out.test.js' },
  { file: 'brain-first-tapestry-authoring.test.js' },
  { file: 'b-coverage-audit-and-disposition.test.js' },
  { file: 'adoption-candidates-queue.test.js' },
  { file: 'inverse-queue-publish-candidates.test.js' },
  { file: 'publish-time-default-stamping.test.js' },
  { file: 'trusted-dictionary.test.js' },
  { file: 'adoption-twins.test.js' },
  { file: 'adoption-raw-event-view.test.js' },
  { file: 'state-on-concept-page.test.js' },
  { file: 'shared-by-me.test.js' },
  { file: 'retire-offering-vocabulary.test.js' },
  { file: 'site-trust-signals.test.js' },
  { file: 'tl-membership-method-selector.test.js' },
  { file: 'tl-weighted-sum-method.test.js' },
  { file: 'tl-certainty-method.test.js' },
  { file: 'tl-treasure-map-panel.test.js' },
  { file: 'tl-treasure-map-optin-publish.test.js' },
  { file: 'neo4j-sizing-override.test.js' },
  { file: 'relay-scan-bounds.test.js' },
  { file: 'honest-broadcast-reporting.test.js' },
  { file: 'honest-publish-reporting.test.js' },
  { file: 'honest-publish-reporting-ci-guard.test.js' },
  { file: 'not-yet-shared-filter.test.js', skipNote: 'preconditions not met' },
  { file: 'share-from-shared-by-me.test.js' },
  { file: 'treasure-map-relay-presence.test.js' },
  { file: 'treasure-map-relay-sync.test.js' },
  { file: 'treasure-map-panel-summary.test.js' },
  { file: 'add-node-as-element-restore.test.js' },
  { file: 'concept-count-canonical.test.js' },
  { file: 'summaries-element-count.test.js' },
  { file: 'dlist-curation-tl-panel.test.js' },
  { file: 'dlist-curation-header-endpoint.test.js' },
  { file: 'dlist-curation-panel.test.js' },
  { file: 'dlist-curation-map-entries.test.js' },
  { file: 'dlist-curation-merge-preserve.test.js' },
  { file: 'my-curated-dlists-page.test.js' },
  { file: 'my-curated-dlists-headers.test.js' },
  { file: 'my-curated-dlists-items.test.js' },
  { file: 'assistant-setup-state.test.js' },
  { file: 'gate-result-record.test.js' },
];

// Suite files that had never been registered in the runner as of 2026-09-12. Listed so
// they are visible rather than silent; their disposition (register or retire) belongs
// to the event-tagging reconciliation (OPEN.md row 38).
const NOT_RUN = 'not run as of 2026-09-12; disposition pending the event-tagging reconciliation (OPEN.md row 38)';
const excluded = [
  { file: 'generalized-tag-pinning.test.js', reason: NOT_RUN },
  { file: 'pinned-notes-display.test.js', reason: NOT_RUN },
  { file: 'signer-guard-rollout.test.js', reason: NOT_RUN },
  { file: 'tag-a-note-modal.test.js', reason: NOT_RUN },
];

module.exports = { suites, excluded };
