/**
 * Treasure-Map (kind 10040) entry classification — ADR tl-treasure-map/0001.
 *
 * First-element grammar: "<kind>" (a generic entry — the whole kind delegated to
 * one publisher) or "<kind>:<name>" (NIP-85 kind:metric for 3038x; reserved
 * named-list override for 3039x, recognized but inert today).
 */

const HEX64 = /^[0-9a-fA-F]{64}$/;
const ENTRY = /^(\d{5})(?::(.+))?$/;

/**
 * Classify one 10040 tag into a display row.
 *
 * @param {Array} tag  raw nostr tag, e.g. ["30382:rank", <pubkey>, <relay>]
 * @returns {{raw: string, kind: number|null, name: string|null,
 *            cls: 'ta'|'tl'|'other', pubkey: string|null, relay: string|null}}
 *   `cls`: 30380–30389 → 'ta', 30390–30399 → 'tl', anything else → 'other'.
 *   A delegation entry without a valid delegate is no delegation: rows whose
 *   second element is not 64-hex classify 'other' regardless of kind (AC-6).
 *   `pubkey`: lowercased 64-hex second element, or null when absent/non-hex.
 *   Never throws on malformed input — unparseable rows come back as 'other'.
 */
export function classifyEntry(tag) {
  const t = Array.isArray(tag) ? tag : [];
  const first = typeof t[0] === 'string' ? t[0] : '';
  const m = first.match(ENTRY);
  const kind = m ? Number(m[1]) : null;
  const name = m && m[2] !== undefined ? m[2] : null;
  const pubkey = typeof t[1] === 'string' && HEX64.test(t[1]) ? t[1].toLowerCase() : null;
  const cls = pubkey === null ? 'other'
    : kind !== null && kind >= 30380 && kind <= 30389 ? 'ta'
    : kind !== null && kind >= 30390 && kind <= 30399 ? 'tl'
    : 'other';
  const relay = typeof t[2] === 'string' && t[2] !== '' ? t[2] : null;
  return { raw: first, kind, name, cls, pubkey, relay };
}

/**
 * The first generic (bare-kind) delegation entry with a valid delegate, else
 * null — ADR §4's first-occurrence rule. Named entries (`"<kind>:<name>"`) and
 * delegate-less rows are inert here (the reservation and the demotion rule).
 */
export function findGenericTlDelegation(tags, kind = 30392) {
  for (const t of (tags || [])) {
    const row = classifyEntry(t);
    if (row.kind === kind && row.name === null && row.pubkey !== null) return row;
  }
  return null;
}

/**
 * The collapsed-line verdict for the pubkey-TL delegation (dlist-curation #1, ADR 0001 §1):
 * `{ status: 'absent'|'external'|'local', label, tone }`, where `label` is the exact text the
 * Trusted Lists panel shows beside its title and `tone` is the colour key (`ok` | `warn` | `none`).
 * Null when there is no baseline to judge against (the signed-in user's assistant has not
 * resolved) — the caller renders nothing, never a guess. Never throws: a delegate-less row or
 * garbage input reads as `absent`, consistent with findGenericTlDelegation.
 */
export function describeTlDelegation(delegation, assistantPubkey) {
  if (typeof assistantPubkey !== 'string' || assistantPubkey === '') return null;
  const pk = delegation && typeof delegation.pubkey === 'string' ? delegation.pubkey : null;
  if (!pk) return { status: 'absent', label: '○ Not set', tone: 'none' };
  if (pk === assistantPubkey) return { status: 'local', label: '✅ Your Tapestry Assistant', tone: 'ok' };
  return { status: 'external', label: `⚠️ Another publisher · ${pk.slice(0, 8)}…${pk.slice(-4)}`, tone: 'warn' };
}

/**
 * Parse a hand-edited Treasure-Map JSON text into the unsigned replacement —
 * the manual-editor path (story 4, re-stamp policy). Honors the edit's
 * kind/tags/content exactly (kind defaults to 10040 when absent; content to
 * ''); drops id/sig (regenerated by signing); re-stamps created_at skew-proof
 * against the event being replaced. Throws Error with a human message on
 * invalid input. The caller adds `pubkey` from the drift-guarded signer.
 */
export function composeManualUpdate(text, oldEvent) {
  let parsed;
  try { parsed = JSON.parse(text); } catch { throw new Error('Not valid JSON.'); }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('The event must be a JSON object.');
  }
  if (!Array.isArray(parsed.tags)) throw new Error('"tags" must be an array.');
  for (const t of parsed.tags) {
    if (!Array.isArray(t) || !t.every((x) => typeof x === 'string')) {
      throw new Error('Every tag must be an array of strings.');
    }
  }
  if (parsed.content !== undefined && typeof parsed.content !== 'string') {
    throw new Error('"content" must be a string.');
  }
  const kind = parsed.kind === undefined ? 10040 : Number(parsed.kind);
  if (!Number.isInteger(kind) || kind < 0) throw new Error('"kind" must be a non-negative integer.');
  return {
    kind,
    created_at: Math.max(Math.floor(Date.now() / 1000), (oldEvent?.created_at || 0) + 1),
    content: parsed.content ?? '',
    tags: parsed.tags.map((t) => [...t]),
  };
}

/**
 * The updated unsigned Map: the first generic `kind` entry replaced in place
 * (later generic duplicates dropped — the writer normalizes to at most one,
 * ADR §3), or the new entry appended when none exists; every other tag copied
 * verbatim, in order. `created_at` is strictly greater than the old event's so
 * a skewed-clock original can never outrank the replacement (relays keep the
 * newest replaceable event).
 */
export function upsertGenericTlTag(event, kind, pubkey, relay) {
  const kindStr = String(kind);
  const entry = [kindStr, pubkey, typeof relay === 'string' ? relay : ''];
  const tags = [];
  let placed = false;
  for (const t of (event?.tags || [])) {
    if (Array.isArray(t) && t[0] === kindStr) {
      if (!placed) { tags.push(entry); placed = true; }
      continue;
    }
    tags.push(Array.isArray(t) ? [...t] : t);
  }
  if (!placed) tags.push(entry);
  return {
    kind: 10040,
    created_at: Math.max(Math.floor(Date.now() / 1000), (event?.created_at || 0) + 1),
    content: event?.content || '',
    tags,
  };
}

/* ── Per-DList curation entries (dlist-curation #5, ADR 0005; wire form: ADR 0002) ── */

const DLIST_ENTRY = /^(39998|39999):(.+)$/;
const RESERVED_DLIST_D = 'dlist-header'; // the blanket designation — never a per-DList entry

/**
 * Every per-DList curation entry on a Map: first element `<kind>:<d-tag>` with kind 39998 or
 * 39999 (split at the FIRST colon — the d-tag may contain colons), the reserved blanket word
 * excluded, and a valid 64-hex delegate (lowercased; a delegate-less row is no entry — story 2's
 * demotion rule). Order preserved; never throws.
 *
 * @returns {Array<{index:number, raw:string, kind:number, d:string, pubkey:string, relay:string|null}>}
 */
export function findDListEntries(tags) {
  const out = [];
  (Array.isArray(tags) ? tags : []).forEach((t, index) => {
    if (!Array.isArray(t) || typeof t[0] !== 'string') return;
    const m = t[0].match(DLIST_ENTRY);
    if (!m || m[2] === RESERVED_DLIST_D) return;
    if (typeof t[1] !== 'string' || !HEX64.test(t[1])) return;
    out.push({
      index, raw: t[0], kind: Number(m[1]), d: m[2], pubkey: t[1].toLowerCase(),
      relay: typeof t[2] === 'string' && t[2] !== '' ? t[2] : null,
    });
  });
  return out;
}

/** The replaceable-event skew rule: strictly after the event being replaced (ADR tl-treasure-map/0001). */
function restamp(event) {
  return Math.max(Math.floor(Date.now() / 1000), (event?.created_at || 0) + 1);
}

/**
 * The updated unsigned Map with the per-DList entry `<kind>:<d>` → `pubkey` @ `relay`: the first
 * entry whose first element is exactly `<kind>:<d>` replaced in place (later duplicates dropped —
 * one entry per kind and d-tag, ADR 0002 §5), or appended when none exists; every other tag copied
 * verbatim, in order; content preserved; empty-string hint when unconfigured (shape preserved).
 */
export function upsertDListEntry(event, kind, d, pubkey, relay) {
  const key = `${kind}:${d}`;
  const entry = [key, pubkey, typeof relay === 'string' ? relay : ''];
  const tags = [];
  let placed = false;
  for (const t of (event?.tags || [])) {
    if (Array.isArray(t) && t[0] === key) {
      if (!placed) { tags.push(entry); placed = true; }
      continue;
    }
    tags.push(Array.isArray(t) ? [...t] : t);
  }
  if (!placed) tags.push(entry);
  return { kind: 10040, created_at: restamp(event), content: event?.content || '', tags };
}

/**
 * The updated unsigned Map with every `<kind>:<d>` entry removed — revocation (ADR 0002 §7): the
 * empowerment is withdrawn; the assistant's header is untouched. Everything else verbatim.
 */
export function removeDListEntry(event, kind, d) {
  const key = `${kind}:${d}`;
  const tags = [];
  for (const t of (event?.tags || [])) {
    if (Array.isArray(t) && t[0] === key) continue;
    tags.push(Array.isArray(t) ? [...t] : t);
  }
  return { kind: 10040, created_at: restamp(event), content: event?.content || '', tags };
}

/**
 * The DList Curation panel's collapsed-line label: every per-DList entry on the Map counts, mine
 * or another assistant's (ADR 0005 sub-decision 2).
 */
export function describeDListCuration(entries) {
  const count = Array.isArray(entries) ? entries.length : 0;
  const label = count === 0 ? 'None yet' : count === 1 ? '1 DList curated' : `${count} DLists curated`;
  return { count, label };
}

/* ── Relay presence (ADR treasure-map-relay-presence/0001) ───────────────── */

/**
 * The relays to check for a Map, unioned from the named `aRelays` groups.
 *
 * Group KEYS are policy (which kinds of relay are worth checking); the URLs inside them are
 * configuration the operator edits at Home > Settings > Relays. A relay listed in two groups
 * yields one row carrying both labels. Order follows `groupKeys`, then position within a group.
 *
 * Never throws: a missing, empty, or malformed group is skipped, so bad config degrades the
 * panel to fewer rows rather than taking the page down.
 *
 * @param {Object|null} aRelays  the settings relay map (from useConfig)
 * @param {string[]} groupKeys   which groups to union
 * @returns {Array<{url: string, groups: string[]}>}
 */
export function buildPresenceTargets(aRelays, groupKeys) {
  const byUrl = new Map();
  for (const key of (Array.isArray(groupKeys) ? groupKeys : [])) {
    const group = aRelays && aRelays[key];
    if (!Array.isArray(group)) continue;
    for (const raw of group) {
      if (typeof raw !== 'string') continue;
      const url = raw.trim();
      if (!/^wss?:\/\/.+/i.test(url)) continue;
      const existing = byUrl.get(url);
      if (existing) {
        if (!existing.groups.includes(key)) existing.groups.push(key);
      } else {
        byUrl.set(url, { url, groups: [key] });
      }
    }
  }
  return Array.from(byUrl.values());
}

/**
 * How a relay's copy relates to the Map on screen.
 *
 * Kind 10040 is replaceable, so "does this relay have it" is not a yes/no: a relay may hold a
 * different version, and a relay serving a stale one silently advertises a delegation the user
 * has already changed.
 *
 * @param {Object|null} displayed  the event being shown ({ id, created_at })
 * @param {Object|null} found      what the relay returned ({ id, created_at })
 * @returns {'same'|'older'|'newer'|'divergent'|null}
 *   `divergent` = a different event with the SAME timestamp — real, and no order can honestly
 *   be claimed. `null` when either side is missing.
 */
export function compareMapVersions(displayed, found) {
  if (!displayed || !found) return null;
  if (typeof displayed.id !== 'string' || typeof found.id !== 'string') return null;
  if (displayed.id === found.id) return 'same';
  const mine = Number(displayed.created_at) || 0;
  const theirs = Number(found.created_at) || 0;
  if (theirs < mine) return 'older';
  if (theirs > mine) return 'newer';
  return 'divergent';
}

/**
 * One-line verdict over a set of relay row states — the panel's status light.
 *
 * Names the most serious finding rather than counting coverage: one relay serving a STALE Map
 * is worse than three relays not having it, because a missing Map means a reader finds nothing
 * while a stale one points them at a delegation the user may already have revoked.
 *
 * Precedence (ADR treasure-map-relay-presence/0003 § Decision):
 *   1. divergent   — any relay holds a different version
 *   2. checking    — else, any relay has not answered yet
 *   3. missing     — else, any relay lacks the Map
 *   4. unreachable — else, any relay could not be reached
 *   5. ok          — else
 *
 * Note that `divergent` sits ABOVE `checking` while everything else sits below it. That is not
 * an oversight: a divergence is already true and no later answer can revoke it, so reporting it
 * early is honest — whereas a missing count can still fall and an all-clear can be withdrawn,
 * so both must wait for the check to finish.
 *
 * Never throws: it runs on every render.
 *
 * @param {Object|null} localEvent  local strfry's copy, the comparison base
 * @param {Array<{status: string, event: Object|null}>} rowStates  one per reported location
 * @returns {{level: string, counts: Object}}
 */
export function summarizePresence(localEvent, rowStates) {
  const rows = Array.isArray(rowStates) ? rowStates : [];
  const counts = {
    divergent: 0, missing: 0, unreachable: 0, agreeing: 0, pending: 0, unjudged: 0,
    total: rows.length,
  };

  for (const row of rows) {
    const status = row && typeof row.status === 'string' ? row.status : 'pending';
    if (status === 'unreachable') counts.unreachable++;
    else if (status === 'absent') counts.missing++;
    else if (status === 'present') {
      const rel = compareMapVersions(localEvent, row.event);
      if (rel === 'same') counts.agreeing++;
      else if (rel !== null) counts.divergent++;
      // rel === null: the relay has a Map, but there is nothing local to compare it against, so
      // it is neither agreement nor divergence. Counted explicitly — an unjudged row must not
      // silently vanish from the tally, or the level could fall through to an all-clear over a
      // row that was never actually judged.
      else counts.unjudged++;
    } else counts.pending++;
  }

  let level;
  if (counts.divergent > 0) level = 'divergent';
  else if (counts.pending > 0) level = 'checking';
  else if (counts.missing > 0) level = 'missing';
  else if (counts.unreachable > 0) level = 'unreachable';
  // `unjudged` sits here — below every real finding, above the all-clear. It must never let the
  // level fall through to `ok` (that would be an all-clear over a row nothing ever judged), but
  // it must not outrank a finding either: the ordinary case of an unjudged row is "the Map is
  // not in local strfry, so relay copies cannot be compared", and there the useful thing to say
  // is that local is missing it — not a "checking" that never resolves.
  else if (counts.unjudged > 0) level = 'checking';
  else level = 'ok';

  return { level, counts };
}

/**
 * Which way, if any, a sync between local strfry and one relay should go.
 *
 * `localEvent` is what LOCAL holds — not necessarily what the page is displaying. When the Map
 * was found on an external relay rather than locally, local holds nothing and the caller must
 * pass null (ADR treasure-map-relay-presence/0002 § Decision).
 *
 * Never throws: it runs during render, once per row.
 *
 * @param {Object|null} localEvent  local strfry's copy ({ id, created_at }) or null
 * @param {Object|null} relayEvent  the relay's copy ({ id, created_at }) or null
 * @returns {{direction: 'push'|'pull'|null, reason: string|null}}
 *   `push` = send local's copy out; `pull` = bring the relay's copy back.
 *   A null direction always carries a reason: `in-sync`, `divergent`, or `nothing-to-sync`.
 */
export function planRelaySync(localEvent, relayEvent) {
  const hasLocal = !!(localEvent && typeof localEvent.id === 'string');
  const hasRelay = !!(relayEvent && typeof relayEvent.id === 'string');

  if (!hasLocal && !hasRelay) return { direction: null, reason: 'nothing-to-sync' };
  if (hasLocal && !hasRelay) return { direction: 'push', reason: null };
  if (!hasLocal && hasRelay) return { direction: 'pull', reason: null };

  switch (compareMapVersions(localEvent, relayEvent)) {
    case 'same': return { direction: null, reason: 'in-sync' };
    case 'older': return { direction: 'push', reason: null };
    case 'newer': return { direction: 'pull', reason: null };
    // Equal created_at, different id. Neither copy is "more recent", so no honest direction
    // label exists — and NIP-01 breaks such a tie by lowest id, so a push might silently
    // no-op. Report it and offer nothing rather than guess on the user's behalf.
    default: return { direction: null, reason: 'divergent' };
  }
}
