/**
 * Treasure-Map (kind 10040) entry classification — ADR tl-treasure-map/0001.
 *
 * First-element grammar: "<kind>" (a generic entry — the whole kind delegated to
 * one publisher) or "<kind>:<name>" (NIP-85 kind:metric for 3038x; reserved
 * named-list override for 3039x, recognized but inert today).
 */

// The house owner of the `b`-value rules (the UI mirror of src/lib/bValueForms.js; ADR
// my-curated-dlists/0003 sub-decision 9). The `.js` extension keeps Node-loaded suites resolving it.
import { classifyBValue, dispositionOf } from './bDisposition.js';

const HEX64 = /^[0-9a-fA-F]{64}$/;
const ENTRY = /^(\d{5})(?::(.+))?$/;

/**
 * Classify one 10040 tag into a display row.
 *
 * @param {Array} tag  raw nostr tag, e.g. ["30382:rank", <pubkey>, <relay>]
 * @returns {{raw: string, kind: number|null, name: string|null,
 *            cls: 'ta'|'tl'|'dlist'|'designation'|'other', pubkey: string|null, relay: string|null}}
 *   `cls`: 30380–30389 → 'ta', 30390–30399 → 'tl', named 39998/39999 → 'dlist' (or 'designation'
 *   for `39998:dlist-header`, ADR dlist-curation/0006), anything else → 'other'.
 *   A delegation entry without a valid delegate is no delegation: rows whose
 *   second element is not 64-hex classify 'other' regardless of kind (AC-6).
 *   `pubkey`: lowercased 64-hex second element, or null when absent/non-hex.
 *   Never throws on malformed input — unparseable rows come back as 'other'.
 */
export function classifyEntry(tag) {
  const t = Array.isArray(tag) ? tag : [];
  const first = typeof t[0] === 'string' ? t[0] : '';
  const m = first.match(ENTRY);
  const kind = m ? Number(m[1]) : null;
  const name = m && m[2] !== undefined ? m[2] : null;
  const pubkey = typeof t[1] === 'string' && HEX64.test(t[1]) ? t[1].toLowerCase() : null;
  // dlist-curation #6 (ADR 0006): a named 39998/39999 entry with a valid delegate is a per-DList
  // curation entry — except the reserved blanket word, which is the TA designation. A bare kind
  // (no d-tag) stays `other`, as the story-2 pins require.
  const cls = pubkey === null ? 'other'
    : (kind === 39998 || kind === 39999) && name !== null && name !== ''
      ? (kind === 39998 && name === 'dlist-header' ? 'designation' : 'dlist')
    : kind !== null && kind >= 30380 && kind <= 30389 ? 'ta'
    : kind !== null && kind >= 30390 && kind <= 30399 ? 'tl'
    : 'other';
  const relay = typeof t[2] === 'string' && t[2] !== '' ? t[2] : null;
  return { raw: first, kind, name, cls, pubkey, relay };
}

/**
 * The first generic (bare-kind) delegation entry with a valid delegate, else
 * null — ADR §4's first-occurrence rule. Named entries (`"<kind>:<name>"`) and
 * delegate-less rows are inert here (the reservation and the demotion rule).
 */
export function findGenericTlDelegation(tags, kind = 30392) {
  for (const t of (tags || [])) {
    const row = classifyEntry(t);
    if (row.kind === kind && row.name === null && row.pubkey !== null) return row;
  }
  return null;
}

/**
 * The collapsed-line verdict for the pubkey-TL delegation (dlist-curation #1, ADR 0001 §1):
 * `{ status: 'absent'|'external'|'local', label, tone }`, where `label` is the exact text the
 * Trusted Lists panel shows beside its title and `tone` is the colour key (`ok` | `warn` | `none`).
 * Null when there is no baseline to judge against (the signed-in user's assistant has not
 * resolved) — the caller renders nothing, never a guess. Never throws: a delegate-less row or
 * garbage input reads as `absent`, consistent with findGenericTlDelegation.
 */
export function describeTlDelegation(delegation, assistantPubkey) {
  if (typeof assistantPubkey !== 'string' || assistantPubkey === '') return null;
  const pk = delegation && typeof delegation.pubkey === 'string' ? delegation.pubkey : null;
  if (!pk) return { status: 'absent', label: '○ Not set', tone: 'none' };
  if (pk === assistantPubkey) return { status: 'local', label: '✅ Your Tapestry Assistant', tone: 'ok' };
  return { status: 'external', label: `⚠️ Another publisher · ${pk.slice(0, 8)}…${pk.slice(-4)}`, tone: 'warn' };
}

/**
 * Parse a hand-edited Treasure-Map JSON text into the unsigned replacement —
 * the manual-editor path (story 4, re-stamp policy). Honors the edit's
 * kind/tags/content exactly (kind defaults to 10040 when absent; content to
 * ''); drops id/sig (regenerated by signing); re-stamps created_at skew-proof
 * against the event being replaced. Throws Error with a human message on
 * invalid input. The caller adds `pubkey` from the drift-guarded signer.
 */
export function composeManualUpdate(text, oldEvent) {
  let parsed;
  try { parsed = JSON.parse(text); } catch { throw new Error('Not valid JSON.'); }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('The event must be a JSON object.');
  }
  if (!Array.isArray(parsed.tags)) throw new Error('"tags" must be an array.');
  for (const t of parsed.tags) {
    if (!Array.isArray(t) || !t.every((x) => typeof x === 'string')) {
      throw new Error('Every tag must be an array of strings.');
    }
  }
  if (parsed.content !== undefined && typeof parsed.content !== 'string') {
    throw new Error('"content" must be a string.');
  }
  const kind = parsed.kind === undefined ? 10040 : Number(parsed.kind);
  if (!Number.isInteger(kind) || kind < 0) throw new Error('"kind" must be a non-negative integer.');
  return {
    kind,
    created_at: Math.max(Math.floor(Date.now() / 1000), (oldEvent?.created_at || 0) + 1),
    content: parsed.content ?? '',
    tags: parsed.tags.map((t) => [...t]),
  };
}

/**
 * The updated unsigned Map: the first generic `kind` entry replaced in place
 * (later generic duplicates dropped — the writer normalizes to at most one,
 * ADR §3), or the new entry appended when none exists; every other tag copied
 * verbatim, in order. `created_at` is strictly greater than the old event's so
 * a skewed-clock original can never outrank the replacement (relays keep the
 * newest replaceable event).
 */
export function upsertGenericTlTag(event, kind, pubkey, relay) {
  const kindStr = String(kind);
  const entry = [kindStr, pubkey, typeof relay === 'string' ? relay : ''];
  const tags = [];
  let placed = false;
  for (const t of (event?.tags || [])) {
    if (Array.isArray(t) && t[0] === kindStr) {
      if (!placed) { tags.push(entry); placed = true; }
      continue;
    }
    tags.push(Array.isArray(t) ? [...t] : t);
  }
  if (!placed) tags.push(entry);
  return {
    kind: 10040,
    created_at: Math.max(Math.floor(Date.now() / 1000), (event?.created_at || 0) + 1),
    content: event?.content || '',
    tags,
  };
}

/* ── Per-DList curation entries (dlist-curation #5, ADR 0005; wire form: ADR 0002) ── */

const DLIST_ENTRY = /^(39998|39999):(.+)$/;
const RESERVED_DLIST_D = 'dlist-header'; // the blanket designation — never a per-DList entry

/**
 * Every per-DList curation entry on a Map: first element `<kind>:<d-tag>` with kind 39998 or
 * 39999 (split at the FIRST colon — the d-tag may contain colons), the reserved blanket word
 * excluded, and a valid 64-hex delegate (lowercased; a delegate-less row is no entry — story 2's
 * demotion rule). Order preserved; never throws.
 *
 * @returns {Array<{index:number, raw:string, kind:number, d:string, pubkey:string, relay:string|null}>}
 */
export function findDListEntries(tags) {
  const out = [];
  (Array.isArray(tags) ? tags : []).forEach((t, index) => {
    if (!Array.isArray(t) || typeof t[0] !== 'string') return;
    const m = t[0].match(DLIST_ENTRY);
    if (!m || m[2] === RESERVED_DLIST_D) return;
    if (typeof t[1] !== 'string' || !HEX64.test(t[1])) return;
    out.push({
      index, raw: t[0], kind: Number(m[1]), d: m[2], pubkey: t[1].toLowerCase(),
      relay: typeof t[2] === 'string' && t[2] !== '' ? t[2] : null,
    });
  });
  return out;
}

/** The replaceable-event skew rule: strictly after the event being replaced (ADR tl-treasure-map/0001). */
function restamp(event) {
  return Math.max(Math.floor(Date.now() / 1000), (event?.created_at || 0) + 1);
}

/**
 * The updated unsigned Map with the per-DList entry `<kind>:<d>` → `pubkey` @ `relay`: the first
 * entry whose first element is exactly `<kind>:<d>` replaced in place (later duplicates dropped —
 * one entry per kind and d-tag, ADR 0002 §5), or appended when none exists; every other tag copied
 * verbatim, in order; content preserved; empty-string hint when unconfigured (shape preserved).
 */
export function upsertDListEntry(event, kind, d, pubkey, relay) {
  const key = `${kind}:${d}`;
  const entry = [key, pubkey, typeof relay === 'string' ? relay : ''];
  const tags = [];
  let placed = false;
  for (const t of (event?.tags || [])) {
    if (Array.isArray(t) && t[0] === key) {
      if (!placed) { tags.push(entry); placed = true; }
      continue;
    }
    tags.push(Array.isArray(t) ? [...t] : t);
  }
  if (!placed) tags.push(entry);
  return { kind: 10040, created_at: restamp(event), content: event?.content || '', tags };
}

/**
 * The updated unsigned Map with every `<kind>:<d>` entry removed — revocation (ADR 0002 §7): the
 * empowerment is withdrawn; the assistant's header is untouched. Everything else verbatim.
 */
export function removeDListEntry(event, kind, d) {
  const key = `${kind}:${d}`;
  const tags = [];
  for (const t of (event?.tags || [])) {
    if (Array.isArray(t) && t[0] === key) continue;
    tags.push(Array.isArray(t) ? [...t] : t);
  }
  return { kind: 10040, created_at: restamp(event), content: event?.content || '', tags };
}

/**
 * The DList Curation panel's collapsed-line label: every per-DList entry on the Map counts, mine
 * or another assistant's (ADR 0005 sub-decision 2).
 */
export function describeDListCuration(entries) {
  const count = Array.isArray(entries) ? entries.length : 0;
  const label = count === 0 ? 'None yet' : count === 1 ? '1 DList curated' : `${count} DLists curated`;
  return { count, label };
}

/* ── Map Entries for per-DList entries (dlist-curation #6, ADR 0006) ────────── */

const A_TAG_FORM = /^\d+:[0-9a-f]{64}:.+$/;

/**
 * First occurrence wins (ADR 0002 §5): every Curated DList row whose raw first element already
 * appeared on an earlier Curated DList row is marked `duplicate: true`; other classes are never
 * marked. Returns new row objects in the same order; never throws.
 */
export function markDuplicateEntries(rows) {
  const seen = new Set();
  return (Array.isArray(rows) ? rows : []).map((r) => {
    if (!r || r.cls !== 'dlist') return { ...(r || {}), duplicate: false };
    const duplicate = seen.has(r.raw);
    seen.add(r.raw);
    return { ...r, duplicate };
  });
}

/**
 * The community header a curation header inherits from: the first `b` tag whose value is an
 * a-tag (the reserved sentinel and event-id values derive nothing — Inherit-From § reserved value);
 * `type` is element 3, `pointer` when absent. Null when there is none.
 */
export function communityPointerOf(header) {
  for (const t of (header && Array.isArray(header.tags) ? header.tags : [])) {
    if (!Array.isArray(t) || t[0] !== 'b' || typeof t[1] !== 'string' || !A_TAG_FORM.test(t[1])) continue;
    return { coord: t[1], type: typeof t[2] === 'string' && t[2] !== '' ? t[2] : 'pointer' };
  }
  return null;
}

/**
 * The details-line verdict for a Curated DList row after the two-step lookup (local strfry, then
 * the row's relay hint only when missing locally): where the header was found, or a warning that
 * names where it was looked for.
 */
export function describeHeaderLookup(row, found, checkedRelay) {
  if (found) return { status: 'found', where: checkedRelay ? 'relay' : 'local' };
  const hint = row && typeof row.relay === 'string' && row.relay !== '' ? row.relay : null;
  return {
    status: 'missing',
    text: hint ? `Header not found locally or on ${hint}` : 'Header not found locally; no relay hint',
  };
}

/* ── My Curated DLists (my-curated-dlists #1, ADR 0001) ─────────────────── */

const CURATED_DLIST_ID = /^(39998|39999):(.+)$/;
const CURATED_DLISTS_BASE = '/tapestry/grapevine/curated-dlists/';

/**
 * The DLists a Map empowers, one row per list: the FIRST entry per raw first element counts (ADR
 * dlist-curation/0002 §5), later repeats are counted into its `ignoredDuplicates`. `mine` is the
 * signed-in user's own assistant — the caller passes `user.assistantPubkey`, never the instance
 * owner's (OPEN.md row 188); with no assistant, nothing is mine. Map order; never throws.
 *
 * @returns {Array<{kind:number, d:string, pubkey:string, relay:string|null, coord:string,
 *                  routeId:string, mine:boolean, ignoredDuplicates:number}>}
 */
export function curatedDListRows(tags, assistantPubkey) {
  const me = typeof assistantPubkey === 'string' && assistantPubkey !== '' ? assistantPubkey.toLowerCase() : null;
  const rows = [];
  const byRaw = new Map();
  for (const e of findDListEntries(tags)) {
    const first = byRaw.get(e.raw);
    if (first) { first.ignoredDuplicates += 1; continue; }
    const row = {
      kind: e.kind, d: e.d, pubkey: e.pubkey, relay: e.relay,
      coord: `${e.kind}:${e.pubkey}:${e.d}`, routeId: e.raw,
      mine: me !== null && e.pubkey === me, ignoredDuplicates: 0,
    };
    byRaw.set(e.raw, row);
    rows.push(row);
  }
  return rows;
}

/**
 * A detail-page route id — the Map entry's own first element, `<kind>:<d>` (split at the FIRST
 * colon; kinds 39998/39999; the reserved blanket word excluded) — or null. The router has already
 * decoded it (ADR 0001 fact 6). Never throws.
 */
export function parseCuratedDListRouteId(id) {
  if (typeof id !== 'string') return null;
  const m = id.match(CURATED_DLIST_ID);
  if (!m || m[2] === RESERVED_DLIST_D) return null;
  return { kind: Number(m[1]), d: m[2] };
}

/** The detail page for a route id: one encoded path segment (colons, slashes, `%` included). */
export function curatedDListPath(routeId) {
  return CURATED_DLISTS_BASE + encodeURIComponent(routeId);
}

/**
 * The detail page's front door (ADR 0001 sub-decision 4): `{ status, row }`. Nothing is decided
 * while auth is still resolving (`checking`, never `signed-out`); then signed-out → no-assistant →
 * bad-id → checking (Map not settled) → map-error → no-map → not-on-map → other-pubkey → ok. `row`
 * is the effective row for the id (so `other-pubkey` can name its pubkey), else null. The list is
 * looked up on the VIEWER's own Map, so a shared URL can never show someone else's curation as
 * theirs. Never throws.
 */
export function curatedDListAccess(input) {
  const { signedIn, authLoading, assistantPubkey, mapStatus, tags, id } = input || {};
  const verdict = (status, row = null) => ({ status, row });
  if (authLoading) return verdict('checking');
  if (!signedIn) return verdict('signed-out');
  if (typeof assistantPubkey !== 'string' || assistantPubkey === '') return verdict('no-assistant');
  const parsed = parseCuratedDListRouteId(id);
  if (!parsed) return verdict('bad-id');
  if (mapStatus === 'error') return verdict('map-error');
  if (mapStatus === 'none') return verdict('no-map');
  if (mapStatus !== 'found') return verdict('checking');
  const routeId = `${parsed.kind}:${parsed.d}`;
  const row = curatedDListRows(tags, assistantPubkey).find((r) => r.routeId === routeId) || null;
  if (!row) return verdict('not-on-map');
  return verdict(row.mine ? 'ok' : 'other-pubkey', row);
}

/**
 * The two-step header lookup (ADR dlist-curation/0006's rule, ADR my-curated-dlists/0001
 * sub-decision 6): local strfry, one `scanLocal` per (kind, pubkey) group, newest per coordinate;
 * then, only for what is still missing, the row's ws/wss relay hint via `fetchRelay(filter, url)`
 * (→ `{ success, events }`), keeping events with the row's kind, author, and d-tag, newest wins.
 * A step that throws or answers without `success` marks the rows it covered `failed: true` — a
 * failed step is never read as "absent". Dependency-injected so it runs without a network; the
 * shape the row-249 chore migrates the Treasure Map page family onto. Never rejects.
 *
 * @returns {Promise<Object<string, {event:Object, where:'local'|'relay', checkedRelay:string|null}
 *                                 | {missing:true, checkedRelay:string|null, failed:boolean}>>}
 */
export async function lookupCurationHeaders(rows, { scanLocal, fetchRelay } = {}) {
  const list = (Array.isArray(rows) ? rows : []).filter((r) => r && typeof r.coord === 'string');
  const out = {};
  const failed = new Set();
  const dOf = (ev) => ev?.tags?.find((t) => Array.isArray(t) && t[0] === 'd')?.[1];

  const groups = new Map();
  for (const r of list) {
    const key = `${r.kind}:${r.pubkey}`;
    if (!groups.has(key)) groups.set(key, { kind: r.kind, pubkey: r.pubkey, rows: [] });
    groups.get(key).rows.push(r);
  }
  for (const g of groups.values()) {
    try {
      const events = await scanLocal({ kinds: [g.kind], authors: [g.pubkey], '#d': g.rows.map((r) => r.d) });
      for (const ev of Array.isArray(events) ? events : []) {
        const d = dOf(ev);
        if (d == null) continue;
        const coord = `${ev.kind}:${ev.pubkey}:${d}`;
        if (!out[coord] || (ev.created_at || 0) > (out[coord].event.created_at || 0)) {
          out[coord] = { event: ev, where: 'local', checkedRelay: null };
        }
      }
    } catch {
      for (const r of g.rows) failed.add(r.coord);
    }
  }

  for (const r of list) {
    if (out[r.coord]) continue;
    const hint = typeof r.relay === 'string' && /^wss?:\/\//i.test(r.relay) ? r.relay : null;
    if (!hint) { out[r.coord] = { missing: true, checkedRelay: null, failed: failed.has(r.coord) }; continue; }
    try {
      const data = await fetchRelay({ kinds: [r.kind], authors: [r.pubkey], '#d': [r.d] }, hint);
      if (!data || !data.success) { out[r.coord] = { missing: true, checkedRelay: hint, failed: true }; continue; }
      const ev = (Array.isArray(data.events) ? data.events : [])
        .filter((e) => e && e.kind === r.kind && e.pubkey === r.pubkey && dOf(e) === r.d)
        .sort((a, b) => (b.created_at || 0) - (a.created_at || 0))[0];
      out[r.coord] = ev
        ? { event: ev, where: 'relay', checkedRelay: hint }
        : { missing: true, checkedRelay: hint, failed: failed.has(r.coord) };
    } catch {
      out[r.coord] = { missing: true, checkedRelay: hint, failed: true };
    }
  }
  return out;
}

/* ── The two headers (my-curated-dlists #2, ADR 0002; `deferred` per ADR 0003) ── */

/**
 * `<kind>:<64-hex pubkey>:<d-tag>` → `{ kind, pubkey, d }` (the d-tag is everything after the second
 * colon), or null — exactly the form `communityPointerOf` accepts (`A_TAG_FORM`). Never throws.
 */
export function parseCoordinate(coord) {
  if (typeof coord !== 'string' || !A_TAG_FORM.test(coord)) return null;
  const i = coord.indexOf(':');
  const j = coord.indexOf(':', i + 1);
  return { kind: Number(coord.slice(0, i)), pubkey: coord.slice(i + 1, j), d: coord.slice(j + 1) };
}

/**
 * What an assistant's curation header says about itself (ADR 0002 sub-decisions 1–3): whether the
 * viewer's assistant authored it (checked, not assumed); the pointer it carries — `communityPointerOf`'s,
 * so Map Entries and this page follow the same one; whether it is deliberately unaffiliated; and the
 * problems, in order `no-b` · `not-a-coordinate` · `wrong-type` · `multiple`. Reported, never
 * fixed. Never throws.
 *
 * `deferred` and the value forms come from the house owner (`bDisposition.js`; ADR 0003 sub-decision
 * 9): `b-tag-deferred` counts only when it stands alone — a real `b` (a coordinate or an event id)
 * supersedes it.
 *
 * @returns {{ authoredByAssistant: boolean, pointer: {coord, type, kind, pubkey, d}|null,
 *             deferred: boolean, problems: string[] }}
 */
export function describeCurationHeader(event, assistantPubkey) {
  const me = typeof assistantPubkey === 'string' && assistantPubkey !== '' ? assistantPubkey.toLowerCase() : null;
  const tags = event && Array.isArray(event.tags) ? event.tags : [];
  const values = tags.filter((t) => Array.isArray(t) && t[0] === 'b').map((t) => t[1]);
  const forms = values.map(classifyBValue);
  const followed = communityPointerOf(event);
  const pointer = followed ? { coord: followed.coord, type: followed.type, ...parseCoordinate(followed.coord) } : null;
  const problems = [];
  if (values.length === 0) problems.push('no-b');
  if (forms.some((f) => f === 'event-id' || f === 'malformed')) problems.push('not-a-coordinate');
  if (pointer && pointer.type !== 'inherit-items') problems.push('wrong-type');
  if (forms.filter((f) => f === 'a-tag').length > 1) problems.push('multiple');
  return {
    authoredByAssistant: !!(me && event && typeof event.pubkey === 'string' && event.pubkey.toLowerCase() === me),
    pointer,
    deferred: dispositionOf(values).deferred,
    problems,
  };
}

/** The row `lookupCurationHeaders` takes to find the shared header a pointer names, at `relay`. */
export function curationPointerRow(pointer, relay) {
  if (!pointer) return null;
  return { kind: pointer.kind, pubkey: pointer.pubkey, d: pointer.d, relay, coord: pointer.coord };
}

/* ── Items (my-curated-dlists #3, ADR 0003) ─────────────────────────────── */

/** How many items one read asks each source for; the local scan reports when it stopped short. */
export const LIST_ITEMS_LIMIT = 500;
const ITEM_KINDS = [9999, 39999];
const tagValue = (event, name) => (Array.isArray(event?.tags) ? event.tags : []).find((t) => Array.isArray(t) && t[0] === name)?.[1];

/**
 * The id Simple Lists opens an item by (`DListItems.jsx`): `39999:<pubkey>:<d>` for an addressable
 * item, the event id otherwise; null for garbage. Never throws.
 */
export function itemRouteId(event) {
  if (!event || typeof event !== 'object' || typeof event.id !== 'string' || event.id === '') return null;
  const d = tagValue(event, 'd');
  if (event.kind === 39999 && typeof d === 'string' && d !== '' && typeof event.pubkey === 'string') {
    return `39999:${event.pubkey}:${d}`;
  }
  return event.id;
}

/**
 * The items of each list coordinate (ADR 0003 sub-decision 3): this instance's strfry through the
 * bounded scan, and the community relay, asked the same filter at once. Only kind 9999/39999 items
 * whose `z` is the coordinate are kept; each item appears once (newest version per coordinate, one per
 * id), `local` when any copy came from this instance. Per source: `local` 'ok' | 'failed' (with the
 * scan's `truncated` / `total`), `relay` 'ok' | 'failed' | 'skipped' (not a ws/wss relay).
 * Dependency-injected; never rejects.
 *
 * @param {string[]} coords
 * @param {{ scanLocal: Function, fetchRelay: Function }} deps  scanLocal(filter) → { events, truncated, total };
 *   fetchRelay(filter, url) → { success, events }
 * @param {string} relay
 */
export async function lookupListItems(coords, { scanLocal, fetchRelay } = {}, relay) {
  const out = {};
  const hint = typeof relay === 'string' && /^wss?:\/\//i.test(relay) ? relay : null;
  const list = (Array.isArray(coords) ? coords : []).filter((c) => typeof c === 'string' && c !== '');
  await Promise.all(list.map(async (coord) => {
    const filter = { kinds: ITEM_KINDS, '#z': [coord], limit: LIST_ITEMS_LIMIT };
    const [local, remote] = await Promise.all([
      (async () => {
        try {
          const env = await scanLocal(filter);
          return { status: 'ok', events: Array.isArray(env?.events) ? env.events : [], truncated: !!env?.truncated, total: env?.total === undefined ? null : env.total };
        } catch {
          return { status: 'failed', events: [], truncated: false, total: null };
        }
      })(),
      (async () => {
        if (!hint) return { status: 'skipped', events: [] };
        try {
          const data = await fetchRelay(filter, hint);
          if (!data || !data.success) return { status: 'failed', events: [] };
          return { status: 'ok', events: Array.isArray(data.events) ? data.events : [] };
        } catch {
          return { status: 'failed', events: [] };
        }
      })(),
    ]);
    const byKey = new Map();
    const take = (event, isLocal) => {
      if (!event || !ITEM_KINDS.includes(event.kind) || typeof event.id !== 'string') return;
      if (!(Array.isArray(event.tags) && event.tags.some((t) => Array.isArray(t) && t[0] === 'z' && t[1] === coord))) return;
      const key = itemRouteId(event);
      const prev = byKey.get(key);
      if (!prev) { byKey.set(key, { event, local: isLocal }); return; }
      const newer = (event.created_at || 0) > (prev.event.created_at || 0) ? event : prev.event;
      byKey.set(key, { event: newer, local: prev.local || isLocal });
    };
    for (const e of local.events) take(e, true);
    for (const e of remote.events) take(e, false);
    out[coord] = { items: [...byKey.values()], local: local.status, truncated: local.truncated, total: local.total, relay: remote.status };
  }));
  return out;
}

const FROM_ORDER = { assistant: 0, other: 1, candidate: 2 };

/**
 * The table's rows (ADR 0003 sub-decisions 1, 2, 5). `mine` are the items pointing at my local DList,
 * `shared` the shared list's (null when not read). By default only my assistant's items; `showOthers`
 * adds everyone else's on my list; `showCandidates` adds shared items my assistant has not copied —
 * "copied" meaning one of MY ASSISTANT'S items carries the shared item's id or coordinate in any tag,
 * at any position. Grouped assistant → other → candidate; by name (case-insensitive), newest first on
 * ties. Never throws.
 *
 * @returns {Array<{ key, from: 'assistant'|'other'|'candidate', name, author, createdAt, routeId, local }>}
 */
export function curatedItemRows(input) {
  const { mine, shared, assistantPubkey, showOthers, showCandidates } = input || {};
  const me = typeof assistantPubkey === 'string' && assistantPubkey !== '' ? assistantPubkey.toLowerCase() : null;
  const valid = (x) => !!(x && x.event && typeof x.event === 'object' && itemRouteId(x.event));
  const mineItems = (Array.isArray(mine) ? mine : []).filter(valid);
  const byMe = (x) => me !== null && typeof x.event.pubkey === 'string' && x.event.pubkey.toLowerCase() === me;
  const toRow = (x, from) => {
    const name = tagValue(x.event, 'name');
    const routeId = itemRouteId(x.event);
    return {
      key: `${from}:${routeId}`, from,
      name: typeof name === 'string' && name.trim() !== '' ? name : '(unnamed)',
      author: x.event.pubkey, createdAt: x.event.created_at || 0, routeId, local: !!x.local,
    };
  };
  const rows = mineItems.filter(byMe).map((x) => toRow(x, 'assistant'));
  if (showOthers) rows.push(...mineItems.filter((x) => !byMe(x)).map((x) => toRow(x, 'other')));
  if (showCandidates && Array.isArray(shared)) {
    const referenced = new Set();
    for (const x of mineItems.filter(byMe)) {
      for (const t of Array.isArray(x.event.tags) ? x.event.tags : []) {
        if (Array.isArray(t)) for (const v of t.slice(1)) if (typeof v === 'string') referenced.add(v);
      }
    }
    for (const x of shared.filter(valid)) {
      const coord = x.event.kind === 39999 ? itemRouteId(x.event) : null;
      if (referenced.has(x.event.id) || (coord && coord !== x.event.id && referenced.has(coord))) continue;
      rows.push(toRow(x, 'candidate'));
    }
  }
  return rows.sort((a, b) => FROM_ORDER[a.from] - FROM_ORDER[b.from]
    || a.name.toLowerCase().localeCompare(b.name.toLowerCase())
    || b.createdAt - a.createdAt);
}

/**
 * Why there is no shared list to draw candidates from — or null when there is one (ADR 0003 note 1):
 * `checking` (the assistant's header not looked up yet) · `failed` · `missing` · `deferred`
 * (deliberately unaffiliated) · `no-pointer`.
 */
export function sharedListUnavailable(assistantLookup, info) {
  if (!assistantLookup) return 'checking';
  if (!assistantLookup.event) return assistantLookup.failed ? 'failed' : 'missing';
  if (!info || !info.pointer) return info && info.deferred ? 'deferred' : 'no-pointer';
  return null;
}

/**
 * The sentence the items table shows when it has no rows (ADR 0003 Amendment 1). "No candidates"
 * is claimed only when the shared list — its lookup record, passed only while it is in view — was
 * read and did not fail on both sources: a failed read is "couldn't check" (its own note), never
 * "empty". Never throws.
 */
export function itemsEmptySentence(input) {
  const { showOthers, shared } = input && typeof input === 'object' ? input : {};
  let sentence = "Your assistant hasn't added any items to this list yet.";
  if (showOthers) sentence += ' No one else has either.';
  const readCleanlyEnough = !!(shared && typeof shared === 'object' && !(shared.local === 'failed' && shared.relay === 'failed'));
  if (readCleanlyEnough) sentence += ' The shared list offers no candidates to inherit.';
  return sentence;
}

/* ── Relay presence (ADR treasure-map-relay-presence/0001) ───────────────── */

/**
 * The relays to check for a Map, unioned from the named `aRelays` groups.
 *
 * Group KEYS are policy (which kinds of relay are worth checking); the URLs inside them are
 * configuration the operator edits at Home > Settings > Relays. A relay listed in two groups
 * yields one row carrying both labels. Order follows `groupKeys`, then position within a group.
 *
 * Never throws: a missing, empty, or malformed group is skipped, so bad config degrades the
 * panel to fewer rows rather than taking the page down.
 *
 * @param {Object|null} aRelays  the settings relay map (from useConfig)
 * @param {string[]} groupKeys   which groups to union
 * @returns {Array<{url: string, groups: string[]}>}
 */
export function buildPresenceTargets(aRelays, groupKeys) {
  const byUrl = new Map();
  for (const key of (Array.isArray(groupKeys) ? groupKeys : [])) {
    const group = aRelays && aRelays[key];
    if (!Array.isArray(group)) continue;
    for (const raw of group) {
      if (typeof raw !== 'string') continue;
      const url = raw.trim();
      if (!/^wss?:\/\/.+/i.test(url)) continue;
      const existing = byUrl.get(url);
      if (existing) {
        if (!existing.groups.includes(key)) existing.groups.push(key);
      } else {
        byUrl.set(url, { url, groups: [key] });
      }
    }
  }
  return Array.from(byUrl.values());
}

/**
 * How a relay's copy relates to the Map on screen.
 *
 * Kind 10040 is replaceable, so "does this relay have it" is not a yes/no: a relay may hold a
 * different version, and a relay serving a stale one silently advertises a delegation the user
 * has already changed.
 *
 * @param {Object|null} displayed  the event being shown ({ id, created_at })
 * @param {Object|null} found      what the relay returned ({ id, created_at })
 * @returns {'same'|'older'|'newer'|'divergent'|null}
 *   `divergent` = a different event with the SAME timestamp — real, and no order can honestly
 *   be claimed. `null` when either side is missing.
 */
export function compareMapVersions(displayed, found) {
  if (!displayed || !found) return null;
  if (typeof displayed.id !== 'string' || typeof found.id !== 'string') return null;
  if (displayed.id === found.id) return 'same';
  const mine = Number(displayed.created_at) || 0;
  const theirs = Number(found.created_at) || 0;
  if (theirs < mine) return 'older';
  if (theirs > mine) return 'newer';
  return 'divergent';
}

/**
 * One-line verdict over a set of relay row states — the panel's status light.
 *
 * Names the most serious finding rather than counting coverage: one relay serving a STALE Map
 * is worse than three relays not having it, because a missing Map means a reader finds nothing
 * while a stale one points them at a delegation the user may already have revoked.
 *
 * Precedence (ADR treasure-map-relay-presence/0003 § Decision):
 *   1. divergent   — any relay holds a different version
 *   2. checking    — else, any relay has not answered yet
 *   3. missing     — else, any relay lacks the Map
 *   4. unreachable — else, any relay could not be reached
 *   5. ok          — else
 *
 * Note that `divergent` sits ABOVE `checking` while everything else sits below it. That is not
 * an oversight: a divergence is already true and no later answer can revoke it, so reporting it
 * early is honest — whereas a missing count can still fall and an all-clear can be withdrawn,
 * so both must wait for the check to finish.
 *
 * Never throws: it runs on every render.
 *
 * @param {Object|null} localEvent  local strfry's copy, the comparison base
 * @param {Array<{status: string, event: Object|null}>} rowStates  one per reported location
 * @returns {{level: string, counts: Object}}
 */
export function summarizePresence(localEvent, rowStates) {
  const rows = Array.isArray(rowStates) ? rowStates : [];
  const counts = {
    divergent: 0, missing: 0, unreachable: 0, agreeing: 0, pending: 0, unjudged: 0,
    total: rows.length,
  };

  for (const row of rows) {
    const status = row && typeof row.status === 'string' ? row.status : 'pending';
    if (status === 'unreachable') counts.unreachable++;
    else if (status === 'absent') counts.missing++;
    else if (status === 'present') {
      const rel = compareMapVersions(localEvent, row.event);
      if (rel === 'same') counts.agreeing++;
      else if (rel !== null) counts.divergent++;
      // rel === null: the relay has a Map, but there is nothing local to compare it against, so
      // it is neither agreement nor divergence. Counted explicitly — an unjudged row must not
      // silently vanish from the tally, or the level could fall through to an all-clear over a
      // row that was never actually judged.
      else counts.unjudged++;
    } else counts.pending++;
  }

  let level;
  if (counts.divergent > 0) level = 'divergent';
  else if (counts.pending > 0) level = 'checking';
  else if (counts.missing > 0) level = 'missing';
  else if (counts.unreachable > 0) level = 'unreachable';
  // `unjudged` sits here — below every real finding, above the all-clear. It must never let the
  // level fall through to `ok` (that would be an all-clear over a row nothing ever judged), but
  // it must not outrank a finding either: the ordinary case of an unjudged row is "the Map is
  // not in local strfry, so relay copies cannot be compared", and there the useful thing to say
  // is that local is missing it — not a "checking" that never resolves.
  else if (counts.unjudged > 0) level = 'checking';
  else level = 'ok';

  return { level, counts };
}

/**
 * Which way, if any, a sync between local strfry and one relay should go.
 *
 * `localEvent` is what LOCAL holds — not necessarily what the page is displaying. When the Map
 * was found on an external relay rather than locally, local holds nothing and the caller must
 * pass null (ADR treasure-map-relay-presence/0002 § Decision).
 *
 * Never throws: it runs during render, once per row.
 *
 * @param {Object|null} localEvent  local strfry's copy ({ id, created_at }) or null
 * @param {Object|null} relayEvent  the relay's copy ({ id, created_at }) or null
 * @returns {{direction: 'push'|'pull'|null, reason: string|null}}
 *   `push` = send local's copy out; `pull` = bring the relay's copy back.
 *   A null direction always carries a reason: `in-sync`, `divergent`, or `nothing-to-sync`.
 */
export function planRelaySync(localEvent, relayEvent) {
  const hasLocal = !!(localEvent && typeof localEvent.id === 'string');
  const hasRelay = !!(relayEvent && typeof relayEvent.id === 'string');

  if (!hasLocal && !hasRelay) return { direction: null, reason: 'nothing-to-sync' };
  if (hasLocal && !hasRelay) return { direction: 'push', reason: null };
  if (!hasLocal && hasRelay) return { direction: 'pull', reason: null };

  switch (compareMapVersions(localEvent, relayEvent)) {
    case 'same': return { direction: null, reason: 'in-sync' };
    case 'older': return { direction: 'push', reason: null };
    case 'newer': return { direction: 'pull', reason: null };
    // Equal created_at, different id. Neither copy is "more recent", so no honest direction
    // label exists — and NIP-01 breaks such a tie by lowest id, so a push might silently
    // no-op. Report it and offer nothing rather than guess on the user's behalf.
    default: return { direction: null, reason: 'divergent' };
  }
}
