import { useState, useMemo } from 'react';
import { useOutletContext, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { createElement } from '../../api/normalize';
import { useCypher } from '../../hooks/useCypher';

export default function NewElement() {
  const { concept, uuid } = useOutletContext();
  const navigate = useNavigate();
  const { user } = useAuth();
  const isOwner = user?.classification === 'owner';

  const [name, setName] = useState('');
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);
  const [showPreview, setShowPreview] = useState(false);

  // Fetch schema to build JSON preview
  const { data: schemaData } = useCypher(`
    MATCH (h:NostrEvent {uuid: '${uuid}'})
    OPTIONAL MATCH (js:JSONSchema)-[:IS_THE_JSON_SCHEMA_FOR]->(h)
    OPTIONAL MATCH (js)-[:HAS_TAG]->(jt:NostrEventTag {type: 'json'})
    OPTIONAL MATCH (h)-[:IS_THE_CONCEPT_FOR]->(sup:Superset)
    RETURN head(collect(jt.value)) AS schemaJson, sup.uuid AS supersetUuid
  `);

  const schema = useMemo(() => {
    const raw = schemaData?.[0]?.schemaJson;
    if (!raw) return null;
    try { return typeof raw === 'string' ? JSON.parse(raw) : raw; }
    catch { return null; }
  }, [schemaData]);

  const supersetUuid = schemaData?.[0]?.supersetUuid;

  // Build the JSON preview based on schema + name
  const previewJson = useMemo(() => {
    const trimmed = name.trim();
    if (!trimmed) return null;

    if (schema && schema.properties && Object.keys(schema.properties).length > 0) {
      const obj = {};
      for (const [prop, def] of Object.entries(schema.properties)) {
        if (prop === 'name' || prop === 'title') {
          obj[prop] = trimmed;
        } else if (prop === 'slug') {
          obj[prop] = trimmed.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
        } else if (prop === 'description') {
          obj[prop] = '';
        } else {
          const t = def.type;
          if (t === 'string')       obj[prop] = '';
          else if (t === 'number' || t === 'integer') obj[prop] = 0;
          else if (t === 'boolean') obj[prop] = false;
          else if (t === 'array')   obj[prop] = [];
          else if (t === 'object')  obj[prop] = {};
          else                      obj[prop] = null;
        }
      }
      return obj;
    }
    return { name: trimmed };
  }, [name, schema]);

  // Build the nostr event preview
  const previewEvent = useMemo(() => {
    const trimmed = name.trim();
    if (!trimmed) return null;

    const dTag = '<auto-generated>';
    const tags = [
      ['d', dTag],
      ['name', trimmed],
      ['z', supersetUuid || '<superset-uuid>'],
    ];
    if (previewJson) {
      tags.push(['json', JSON.stringify(previewJson)]);
    }

    return {
      kind: 39999,
      pubkey: '<tapestry-assistant>',
      created_at: '<now>',
      tags,
      content: '',
    };
  }, [name, supersetUuid, previewJson]);

  async function handleSubmit(e) {
    e.preventDefault();
    if (!name.trim()) return;
    setCreating(true);
    setError(null);
    setResult(null);
    try {
      const res = await createElement({
        concept: concept.name,
        name: name.trim(),
      });
      setResult(res);
    } catch (err) {
      setError(err.message);
    } finally {
      setCreating(false);
    }
  }

  return (
    <div>
      <h2>New Element</h2>
      <p style={{ opacity: 0.7 }}>
        Add a new element to the <strong>{concept?.name}</strong> concept.
      </p>

      {!isOwner && (
        <div className="health-banner health-warn" style={{ marginBottom: '1.5rem' }}>
          <span className="health-banner-icon">🔒</span>
          <span>Sign in as owner to create elements.</span>
        </div>
      )}

      {result ? (
        <div>
          <div className="health-banner health-pass" style={{ marginBottom: '1.5rem' }}>
            <span className="health-banner-icon">✅</span>
            <span className="health-banner-label">Element Created!</span>
          </div>

          <table className="data-table">
            <tbody>
              <tr><td><strong>Name</strong></td><td>{result.element.name}</td></tr>
              <tr><td><strong>UUID</strong></td><td><code className="uuid-short">{result.element.uuid}</code></td></tr>
              <tr><td><strong>Concept</strong></td><td>{result.element.concept}</td></tr>
            </tbody>
          </table>

          <div style={{ marginTop: '1.5rem', display: 'flex', gap: '1rem' }}>
            <button
              className="btn"
              onClick={() => navigate(`/kg/nodes/${encodeURIComponent(result.element.uuid)}`)}
            >
              🔵 View Node
            </button>
            <button
              className="btn"
              onClick={() => navigate(`/kg/concepts/${encodeURIComponent(uuid)}/elements`)}
            >
              📋 Back to Elements
            </button>
            <button
              className="btn btn-primary"
              onClick={() => { setResult(null); setName(''); setError(null); setShowPreview(false); }}
            >
              ➕ Add Another
            </button>
          </div>
        </div>
      ) : (
        <form onSubmit={handleSubmit} className="new-concept-form">
          <div className="form-field">
            <label htmlFor="elem-name">Name <span className="required">*</span></label>
            <input
              id="elem-name"
              type="text"
              value={name}
              onChange={e => setName(e.target.value)}
              placeholder={`e.g. a specific ${concept?.name || 'item'}`}
              required
              autoFocus
              disabled={creating}
            />
          </div>

          {error && (
            <div className="health-banner health-fail" style={{ marginTop: '1rem' }}>
              <span className="health-banner-icon">❌</span>
              <span>{error}</span>
            </div>
          )}

          <div style={{ marginTop: '1.5rem', display: 'flex', gap: '1rem', alignItems: 'center' }}>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={!name.trim() || creating || !isOwner}
              title={!isOwner ? 'Sign in as owner to create elements' : ''}
            >
              {creating ? '⏳ Creating element…' : '➕ Add Element'}
            </button>
            {name.trim() && (
              <button
                type="button"
                className="btn"
                onClick={() => setShowPreview(p => !p)}
              >
                {showPreview ? '🔽 Hide Preview' : '▶️ Show Preview'}
              </button>
            )}
          </div>

          {showPreview && previewJson && (
            <div style={{ marginTop: '1.5rem' }}>
              <h3 style={{ fontSize: '1rem', marginBottom: '0.5rem' }}>📋 JSON Data Preview</h3>
              <pre className="json-block">{JSON.stringify(previewJson, null, 2)}</pre>

              <h3 style={{ fontSize: '1rem', marginTop: '1.5rem', marginBottom: '0.5rem' }}>📨 Nostr Event Preview</h3>
              <pre className="json-block">{JSON.stringify(previewEvent, null, 2)}</pre>
            </div>
          )}
        </form>
      )}
    </div>
  );
}
